using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DahuaAttendanceAPI.Migrations
{
    /// <inheritdoc />
    public partial class FixPendingModelChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // The identity/column alterations were autogenerated but are not required
            // for this migration. Altering IDENTITY on existing columns is not supported
            // without drop/recreate. We only apply the non-destructive operations below.

            // Add check constraint only if it does not already exist
            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_AttendanceUserFaces_FaceIndex')
BEGIN
    ALTER TABLE [AttendanceUserFaces] ADD CONSTRAINT [CK_AttendanceUserFaces_FaceIndex] CHECK ([FaceIndex] IN (1,2));
END
");

            // Add foreign key only if it does not already exist
            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ApplicationUsers_AttendanceUsers_AttendanceUserId')
BEGIN
    ALTER TABLE [ApplicationUsers] ADD CONSTRAINT [FK_ApplicationUsers_AttendanceUsers_AttendanceUserId]
    FOREIGN KEY ([AttendanceUserId]) REFERENCES [AttendanceUsers]([Id]) ON DELETE NO ACTION;
END
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove the FK and check constraint added in Up
            // Drop foreign key if it exists
            migrationBuilder.Sql(@"
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ApplicationUsers_AttendanceUsers_AttendanceUserId')
BEGIN
    ALTER TABLE [ApplicationUsers] DROP CONSTRAINT [FK_ApplicationUsers_AttendanceUsers_AttendanceUserId];
END
");

            // Drop check constraint if it exists
            migrationBuilder.Sql(@"
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_AttendanceUserFaces_FaceIndex')
BEGIN
    ALTER TABLE [AttendanceUserFaces] DROP CONSTRAINT [CK_AttendanceUserFaces_FaceIndex];
END
");
        }
    }
}
